// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package services

import (
	"github.com/apfgijon/cartones/internal/pkg/A-comunication/bot"
	"github.com/apfgijon/cartones/internal/pkg/A-comunication/client"
	"github.com/apfgijon/cartones/internal/pkg/B-commands/commands/commandsv1"
	"github.com/apfgijon/cartones/pkg/covid"
	"github.com/apfgijon/cartones/pkg/pokemon"
)

// Injectors from wire.go:

func InitializeBot(communication client.Communication) (bot.Bot, error) {
	pokeInfo := pokemon.NewPokemonImpl()
	covidInfo := covid.NewCovidApi()
	commandsCommands := commands.NewCommandImpl(pokeInfo, covidInfo)
	botBot := bot.NewGeneralBot(commandsCommands, communication)
	return botBot, nil
}
