// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package services

import (
	"github.com/apfgijon/cartones/internal/pkg/A-comunication/bot"
	"github.com/apfgijon/cartones/internal/pkg/A-comunication/client"
	"github.com/apfgijon/cartones/internal/pkg/B-commands/commands/commandsv1"
	"github.com/apfgijon/cartones/internal/pkg/C-style/prov"
	"github.com/apfgijon/cartones/internal/pkg/D-filesystem/filesystem"
	"github.com/apfgijon/cartones/pkg/cartongen"
	"github.com/apfgijon/cartones/pkg/covid"
	"github.com/apfgijon/cartones/pkg/pokemon"
)

// Injectors from wire.go:

func InitializeBot(c client.Communication, pokeGame string) (bot.Bot, error) {
	pokeInfo, err := pokemon.NewPokemonImpl(pokeGame)
	if err != nil {
		return nil, err
	}
	covidInfo, err := covid.NewCovidApi()
	if err != nil {
		return nil, err
	}
	carton := cartongen.NewCartonv1()
	fileProvider := filesystem.NewFileProvider()
	messageProvider, err := prov.NewMessageProoviderv1(pokeInfo, covidInfo, carton, fileProvider)
	if err != nil {
		return nil, err
	}
	commandsCommands, err := commands.NewCommandImpl(messageProvider)
	if err != nil {
		return nil, err
	}
	botBot, err := bot.NewGeneralBot(commandsCommands, c)
	if err != nil {
		return nil, err
	}
	return botBot, nil
}
